default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: secret

development:
  <<: *default
  database: shorturl-development

test:
  <<: *default
  database: shorturl-test

production:
  <<: *default
  database: shorturl-production
  username:
  password:
  host:
